# For public, HTTPS servers.
version: '3'

services:

  maintenance:
    environment:
      - ETA=2 hours
      - DATE_STR=
      - DATE_ISO=
      - EMAIL=support@kobo.local
    ports:
      - 80:80
